Test date utilities
hackforla/lucky-parking pull request #604
Opened 2023-11-23 21:42 UTC by glenflorendo

### Description

This PR provides complete testing of the date utility functions.

```
Date Utilities
    calculateDateRange
      ✓ calculates one year to now (2 ms)
      ✓ calculates year to now
      ✓ calculates three months to now (1 ms)
      ✓ calculates one month to now
    formatToMiddleEndian
      ✓ formats to middle-endian date format  (3 ms)
    formatToRangeString
      ✓ formats to date range string
```

### Related Issues

Resolves #585 

### Testing

- Ran existing testing suites
- Wrote new tests

```
-----------------------------------------------|---------|----------|---------|---------|-----------------------
File                                           | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s     
-----------------------------------------------|---------|----------|---------|---------|-----------------------
 src/shared/lib/utilities                      |   60.71 |    57.14 |      50 |   68.42 |                       
  date.ts                                      |     100 |      100 |     100 |     100 |                       
```

### Checklist

- [x] I have followed all conventions outlined in our documentation.
- [x] I have fully tested my changes and confirmed that all new and existing tests pass.
- [x] I have written meaningful commit messages for all changes.
- [x] I have linted and formatted my changes to follow the code style of this repository.
- [x] I have updated our documentation, accordingly.
- [x] I have checked currently opened pull requests to ensure that there are no pending pull request for the same changes or issues.
- [x] I have confirmed that this pull request fully meets the acceptance criteria for all related issues listed above.

2023-11-27 23:55 UTC, gibsonliketheguitar requested changes

2023-11-28 01:44 UTC, glenflorendo commented on packages/website/src/shared/lib/utilities/date.test.ts
> +      expect(formatToMiddleEndian(new Date("1999-12-31"))).toStrictEqual("12/31/1999");
Probably not. The `.toEqual` matcher should suffice, but I don't think `.toStrictEqual` does any harm to strings and keeps things consistent across our tests. We can keep it as is, unless you feel strongly that we should change it to `.toEqual` or something else.

2023-11-28 22:00 UTC, gibsonliketheguitar commented on packages/website/src/shared/lib/utilities/date.test.ts
> +      expect(formatToMiddleEndian(new Date("1999-12-31"))).toStrictEqual("12/31/1999");
in that case, If it works it works, no changes needed

2023-11-28 22:00 UTC, gibsonliketheguitar approved these changes

2023-11-28 22:13 UTC, merged