Feat-630 - Redesign of Date Range Picker
hackforla/lucky-parking pull request #651
Opened 2024-04-01 20:39 UTC by gibsonliketheguitar

### Description

Redesign Implementation of calendar month.
- Calendar app code was cannibalize and 2 month calendar was created along with utility functions
- Added suggestion tab to allow user to select presets
### Related Issues

Resolves #630 

### Testing

- Ran testing suites.
```
  Date Range 2 month Calendar
    ✓ renders Back Arrow Icon (45 ms)
    ✓ renders Forward Arrow Icon (9 ms)
    ✓ renders current month and next month (14 ms)
    ✓ render current month's year and next month's year (13 ms)
  Date Range Call to Action 
    ✓ renders current month and next month (19 ms)
    ✓ render December 2024 and January 2025 when Forward Arrow is pressed (224 ms)
    ✓ render October 2024 and November 2024 when Forward Arrow is pressed (52 ms)
    
    Date Range Suggestions Radio Group
    ✓ renders radio group and all it's options (17 ms)
```

### Checklist

- [x] I have followed all conventions outlined in our documentation.
- [ ] I have fully tested my changes and confirmed that all new and existing tests pass.
- [x] I have written meaningful commit messages for all changes.
- [x] I have linted and formatted my changes to follow the code style of this repository.
- [x] I have updated our documentation, accordingly.
- [x] I have checked currently opened pull requests to ensure that there are no pending pull request for the same changes or issues.
- [x] I have confirmed that this pull request fully meets the acceptance criteria for all related issues listed above.

2024-04-06 22:39 UTC, glenflorendo requested changes
Solid work. There are just a few things to fix, then it should be all ready to merge!

2024-04-06 22:39 UTC, glenflorendo commented on packages/ui/src/components/date-picker/date-picker-calendar.tsx
> +                {["M", "T", "W", "T", "F", "S", "S"].map((ele: string, index: number) => (
The week should start with "S" for "Sunday".

2024-04-06 22:39 UTC, glenflorendo commented on packages/ui/src/components/date-picker/date-picker-calendar.tsx
> +            <span aria-label="first-date-month"> {MONTH_NAMES[month]} </span>
The calendar titles should be centered aligned with the calendar.

2024-04-06 22:39 UTC, glenflorendo commented on packages/ui/src/components/date-picker/date-picker-suggestions.tsx
> +  "MONTHS_3" = "3 Months",
This should be Past 3 Months.

2024-04-06 22:39 UTC, glenflorendo commented on packages/ui/src/components/date-picker/date-picker-suggestions.tsx
> +  "MONTHS_1" = "1 Month",
This should be past 1 Month.

2024-04-09 05:03 UTC, gibsonliketheguitar commented
Feeling nervous about the force push. Should I roll it back?

2024-04-21 18:31 UTC, merged